#:import ZBarCam kivy_garden.zbarcam.ZBarCam
#:import ZBarSymbol pyzbar.pyzbar.ZBarSymbol


<ZBar>:
    orientation: 'vertical'
    Button:
        text: 'Get QR-code'
        on_press: root.get_qrcode()
    Label:
        id: label
        text: 'waiting for qr-code'



<ZBarPopup>:
    ZBarCam:
        id: zbarcam
        parent_popup: root
        # optional, by default checks all types
        code_types: ZBarSymbol.QRCODE, ZBarSymbol.EAN13
